### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by hernanytec** [hernanytec/vitrine-filmes#1]
# Página inicial
- [x] Vizualizar lista de filmes.
   - [x] Exibir 10 filmes e paginar o restante.
- [x] Campo de pesquisa pelo nome.
- [x] Ao clicar em um dos filmes o usuário deve ser redirecionado para uma página de detalhes. 

# Página de detalhes do filme
- [x] Devem ser exibidas as seguintes informações: imagem, nome, descrição completa, duração, avaliação, cast.
